### ISSUE TITLE
misc. comments

### ISSUE THREAD

**Issue by raisjn** [mrichards42/remarkable_puzzles#10]
* game selector scene looks great! i just used resim to play with it. 
* seems like fb needs a dither stash for pushing/popping dither modes
* i'm confused why you stop propagation for on_mouse_down. also confused why you make everything dirty for mouse events in same class
* i think help should be the word 'help' or 'how to play' (maybe in the bottom right?), because i shared the game with someone and they said 'i don't know how to play any of these games' and i told them to use the question mark
* what's up with tangle - i have not managed to move a point more than 1 or 2mm
* more games?

**Comment by mrichards42** [comment]
> seems like fb needs a dither stash for pushing/popping dither modes

yeah, that's a great idea. I've seen a pattern where you use the stack to manage this -- i.e. a tiny helper class that restores the previous dithering mode in its destructor.

> i'm confused why you stop propagation for on_mouse_down. also confused why you make everything dirty for mouse events in same class

I blindly copied this from [ui::Button](https://github.com/rmkit-dev/rmkit/blob/ce23cb740cb15e43a44b398fb3c2f4232c570298/src/rmkit/ui/button.cpy#L51-L65), although I found that at least stopping propagation in on_mouse_move meant that the hover effect stuck if I dragged my finger across several buttons, so I removed that part.

> i think help should be the word 'help' or 'how to play' (maybe in the bottom right?), because i shared the game with someone and they said 'i don't know how to play any of these games' and i told them to use the question mark

Yeah, good call that help could be more visible. I've also thought about popping up help the first time you open a puzzle.

> what's up with tangle - i have not managed to move a point more than 1 or 2mm

tangle only works with dragging, and I still haven't merged that code since I'm still thinking about a few things. but I think if you merge in #7 locally it should work.

> more games?

yeah! any of the puzzles that are "keyboard" based (like solo/sudoku, keen/kenken, unequal, towers) will take some more thinking, as will the ones that are very animation heavy (twiddle, flip) or color heavy (map, flood, guess/mastermind), but there's probably still some low-hanging fruit that would just work. Maybe some good next candidates are bridges, pegs, signpost, rectangles, tents, tracks.

**Comment by raisjn** [comment]
> yeah, that's a great idea. I've seen a pattern where you use the stack to manage this -- i.e. a tiny helper class that restores the previous dithering mode in its destructor.

shipit

> but there's probably still some low-hanging fruit that would just work

~~i'm quite partial to `undead` game~~ EDIT: just tried it, needs extra buttons

> tangle only works with dragging, and I still haven't merged that code since I'm still thinking about a few things. but I think if you merge in #7 locally it should work.

EDIT: nvm 😕   ~~is input stuff waiting on me?~~

**Comment by mrichards42** [comment]
Yeah, undead falls under the "keyboard-ish" category unfortunately. re: dragging, I'm still thinking about the general case of how to separate longpress/shortpress from drag. The code I have in this repo solves this particular case for puzzles, but I don't think it's quite right in general. Might make sense to merge that PR just to get it working for puzzles while I think more about https://github.com/rmkit-dev/rmkit/pull/87

**Comment by raisjn** [comment]
i'll still keep the FB dither in mind, but most questions answered
