### ISSUE TITLE
Create new release?

### ISSUE THREAD

**Issue by Eeems** [mrichards42/remarkable_puzzles#19]
It looks like the latest release was in 2021, there have been several updates since then. Could you tag a new release? I'd like to get the [toltec package](https://github.com/toltec-dev/toltec/blob/stable/package/puzzles/package) updated.

**Comment by Eeems** [comment]
@mrichards42 poke?

**Comment by mrichards42** [comment]
@Eeems there haven't been any substantive changes, the only [updates since the last release](https://github.com/mrichards42/remarkable_puzzles/compare/v0.2.2...HEAD) have been updating rmkit twice. Is the current release going to stop working with the framebuffer changes?

**Comment by Eeems** [comment]
Yes, the current release doesn't work without the rmkit upgrade with my linked per-application framebuffer changes.

**Comment by Eeems** [comment]
@mrichards42 poke?

**Comment by Eeems** [comment]
@mrichards42 poke again

**Comment by mrichards42** [comment]
Hey @Eeems sorry, time has been short for a while, and I haven't been using puzzles much anyways. I don't remember all the details about how I set up CI originally, but it looks like the github actions build is running on `ghcr.io/toltec-dev/python:latest`. It seems like somewhere between 5 months ago and 3 months ago there was a change in that image that broke the build (foolish of me to not pin the version of course). FWIW based on the table in https://github.com/toltec-dev/toolchain I'm not sure what image I should be building against (but I'm guessing it's not 1.4 like I have in the Dockerfile in this repo 🙂). If you or @raisjn could help fix that build I'd be more than happy to tag a new release whenever.

More details:

The last successful build from [5 months ago](https://github.com/mrichards42/remarkable_puzzles/actions/runs/5663176917/job/15344466640) unfortunately doesn't have logs any more.

The [most recent broken build](https://github.com/mrichards42/remarkable_puzzles/actions/runs/6138177583/job/16654804334) fails on I'm assuming `pip3 install okp` since the error ends up being

```
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
error: externally-managed-environment
```

... and it looks like maybe the solution is creating a virtual env?

**Comment by Eeems** [comment]
You can find the version tags to pin your image to here: https://github.com/toltec-dev/toolchain/releases

My guess is that 5 months ago you were using v2.3.2, and manually running through the steps in the container seems to work as expected.

**Comment by Eeems** [comment]
I opened #21 to pin the version.

**Comment by mrichards42** [comment]
New release [v0.2.4](https://github.com/mrichards42/remarkable_puzzles/releases/tag/v0.2.4)! Thanks for your help identifying the right image to pin to.
